#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket"
        aesdchar_load
        start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stop aesdsocket"
        start-stop-daemon -K -n aesdsocket -s TERM
        aesdchar_unload
        ;;
esac

exit 0

